In [42]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import scipy.stats as stats
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2 
from sklearn.preprocessing import MinMaxScaler

In [43]:
df=pd.read_csv('Compiled_descriptors.csv')

In [44]:
df=df.iloc[:,1:]

In [45]:
df

,MW,AMW,Sv,Mv,Me,Mp,Mi,GD,nTA,nBM,...,PDI,BLTF96,DLS_02,DLS_03,DLS_04,DLS_06,DLS_cons,LLS_01,LLS_02,Class
0,359.4,8.357,28.24,0.657,1.034,0.658,1.123,0.083,7.0,15.0,...,0.845,-2.11,0.83,0.83,0.7,0.67,0.61,0.17,0.88,0
1,368.4,7.839,30.56,0.650,1.017,0.667,1.115,0.080,6.0,16.0,...,0.880,-2.87,1.00,1.00,0.6,1.00,0.80,0.33,1.00,1
2,370.5,6.501,33.76,0.592,0.992,0.636,1.124,0.080,8.0,10.0,...,0.886,-5.32,0.83,1.00,1.0,1.00,0.94,0.17,0.88,2
3,249.3,7.334,22.23,0.654,0.988,0.694,1.117,0.123,0.0,17.0,...,1.018,-4.72,1.00,1.00,0.6,1.00,0.87,0.67,1.00,2
4,269.8,8.702,21.53,0.694,1.002,0.732,1.113,0.123,1.0,17.0,...,1.023,-4.95,1.00,1.00,0.6,1.00,0.76,0.83,1.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,304.3,8.949,23.16,0.681,1.047,0.669,1.116,0.104,6.0,13.0,...,0.841,-1.32,1.00,1.00,0.4,1.00,0.77,0.33,1.00,2
565,365.6,7.947,30.42,0.661,0.984,0.729,1.104,0.093,2.0,15.0,...,1.023,-4.75,1.00,1.00,0.8,1.00,0.90,0.33,1.00,1
566,265.4,6.805,24.28,0.623,0.984,0.669,1.123,0.116,4.0,16.0,...,1.000,-3.84,1.00,1.00,0.8,1.00,0.90,1.00,1.00,0
567,292.3,8.119,21.45,0.596,1.056,0.583,1.155,0.100,8.0,4.0,...,0.769,-0.24,0.67,0.83,0.9,0.67,0.72,0.33,0.75,2
568,198.3,6.838,18.20,0.628,0.983,0.675,1.120,0.162,1.0,11.0,...,1.052,-3.27,0.67,0.83,0.8,1.00,0.83,1.00,1.00,0

In [46]:
x=df.drop('Class',axis=1)
y=df['Class']

In [47]:
scalar= MinMaxScaler()
scaled_data=scalar.fit_transform(x,y)

In [48]:
new_df=pd.DataFrame(scaled_data, columns=df.columns[:-1])

In [49]:
new_df['Class']=df['Class']

In [50]:
x_trf=new_df.drop('Class',axis=1)
y_trf=new_df['Class']

In [51]:
k=30
features_chi2=SelectKBest(chi2, k=k)
x_new=features_chi2.fit_transform(x_trf,y_trf)
selected_features=df.columns[:-1][features_chi2.get_support()]

In [52]:
df['Class']=new_df['Class']

In [53]:
df

,MW,AMW,Sv,Mv,Me,Mp,Mi,GD,nTA,nBM,...,PDI,BLTF96,DLS_02,DLS_03,DLS_04,DLS_06,DLS_cons,LLS_01,LLS_02,Class
0,359.4,8.357,28.24,0.657,1.034,0.658,1.123,0.083,7.0,15.0,...,0.845,-2.11,0.83,0.83,0.7,0.67,0.61,0.17,0.88,0
1,368.4,7.839,30.56,0.650,1.017,0.667,1.115,0.080,6.0,16.0,...,0.880,-2.87,1.00,1.00,0.6,1.00,0.80,0.33,1.00,1
2,370.5,6.501,33.76,0.592,0.992,0.636,1.124,0.080,8.0,10.0,...,0.886,-5.32,0.83,1.00,1.0,1.00,0.94,0.17,0.88,2
3,249.3,7.334,22.23,0.654,0.988,0.694,1.117,0.123,0.0,17.0,...,1.018,-4.72,1.00,1.00,0.6,1.00,0.87,0.67,1.00,2
4,269.8,8.702,21.53,0.694,1.002,0.732,1.113,0.123,1.0,17.0,...,1.023,-4.95,1.00,1.00,0.6,1.00,0.76,0.83,1.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,304.3,8.949,23.16,0.681,1.047,0.669,1.116,0.104,6.0,13.0,...,0.841,-1.32,1.00,1.00,0.4,1.00,0.77,0.33,1.00,2
565,365.6,7.947,30.42,0.661,0.984,0.729,1.104,0.093,2.0,15.0,...,1.023,-4.75,1.00,1.00,0.8,1.00,0.90,0.33,1.00,1
566,265.4,6.805,24.28,0.623,0.984,0.669,1.123,0.116,4.0,16.0,...,1.000,-3.84,1.00,1.00,0.8,1.00,0.90,1.00,1.00,0
567,292.3,8.119,21.45,0.596,1.056,0.583,1.155,0.100,8.0,4.0,...,0.769,-0.24,0.67,0.83,0.9,0.67,0.72,0.33,0.75,2
568,198.3,6.838,18.20,0.628,0.983,0.675,1.120,0.162,1.0,11.0,...,1.052,-3.27,0.67,0.83,0.8,1.00,0.83,1.00,1.00,0

In [184]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import cross_val_score

In [55]:
clf2=RandomForestClassifier()

In [59]:
x=df[j].drop('Class', axis=1)
y=df['Class']

In [60]:
np.mean(cross_val_score(clf2,x,y,scoring='accuracy',cv=10))

0.5905388471177944

In [61]:
chi2_values, p_values = chi2(x_trf, y_trf)

In [62]:
chi2_df = pd.DataFrame({
    'Feature': x_trf.columns,
    'Chi2 Value': chi2_values,
    'P-Value': p_values
})

In [63]:
chi2_df

      Feature  Chi2 Value   P-Value
0          MW    0.101096  0.950708
1         AMW    0.691412  0.707720
2          Sv    0.076456  0.962494
3          Mv    0.122138  0.940758
4          Me    0.890228  0.640751
..        ...         ...       ...
732    DLS_04    0.490233  0.782613
733    DLS_06    0.146795  0.929231
734  DLS_cons    0.069024  0.966077
735    LLS_01    0.186280  0.911066
736    LLS_02    0.311764  0.855660

[737 rows x 3 columns]

In [64]:
mask1=chi2_df['P-Value']<=0.05
mask2=chi2_df['Chi2 Value']>=9.00

In [70]:
j=chi2_df[mask1&mask2]['Feature'].tolist()

In [71]:
len(j)

13

In [88]:
j=chi2_df[mask1|mask2]['Feature'].tolist()

In [89]:
len(j)

26

In [90]:
final_df=new_df[j]

In [91]:
final_df['Class']=new_df['Class']

C:\Users\Akshat\AppData\Local\Temp\ipykernel_18108\695168134.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Class']=new_df['Class']

In [92]:
final_df

,nF,nX,P_VSA_ppp_hal,nR=Cs,nR=Ct,C-005,C-006,C-016,H-053,O-060,...,T(F..F),F03[C-S],F04[N-Cl],F05[C-S],F05[N-F],F06[C-F],F07[C-F],F07[C-Br],F10[C-F],Class
0,0.0,0.000000,0.00,0.333333,0.000000,0.000000,0.000000,0.333333,0.0,0.000000,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.000000,0.00,1.000000,0.000000,0.333333,0.000000,0.833333,0.0,0.333333,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.000000,0.00,0.666667,0.333333,0.000000,0.000000,0.666667,0.0,0.166667,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,2
3,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.066667,0.000000,0.0,0.000000,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,2
4,0.0,0.166667,0.25,0.000000,0.000000,0.000000,0.066667,0.000000,0.0,0.000000,...,0.0,0.000000,0.25,0.000000,0.0,0.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.166667,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,2
565,0.0,0.000000,0.00,0.500000,0.000000,0.000000,0.133333,0.500000,0.0,0.000000,...,0.0,0.888889,0.00,0.181818,0.0,0.0,0.0,0.0,0.0,1
566,0.0,0.000000,0.00,0.000000,0.000000,0.666667,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0
567,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.400000,0.000000,0.0,0.000000,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,2
568,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0

In [78]:
chi2_df[mask1&mask2]

          Feature  Chi2 Value       P-Value
16             nF   11.747607  2.812157e-03
20             nX   10.710502  4.723284e-03
512         C-005   17.659518  1.463135e-04
513         C-006    9.201925  1.004217e-02
515         C-016   15.475668  4.360150e-04
534         SdsCH    9.065954  1.074863e-02
565  CATS2D_04_DA   11.187033  3.721916e-03
566  CATS2D_05_DA   12.286795  2.147614e-03
632       T(O..F)   31.640958  1.346646e-07
638       T(F..F)   27.747326  9.435061e-07
676      F06[C-F]   19.866188  4.854137e-05
685      F07[C-F]   11.453760  3.257224e-03
714      F10[C-F]   14.709421  6.395727e-04

In [95]:
j=['nF',
 'nX',
 'P_VSA_ppp_hal',
 'SM03_EA(dm)',
 'nR=Cs',
 'nR=Ct',
 'C-005',
 'C-006',
 'C-016',
 'H-053',
 'O-060',
 'SdsCH',
 'CATS2D_04_DD',
 'CATS2D_04_DA',
 'CATS2D_05_DA',
 'CATS2D_07_DL',
 'CATS2D_03_PL',
 'T(O..F)',
 'T(F..F)',
 'F03[C-S]',
 'F04[N-Cl]',
 'F05[C-S]',
 'F05[N-N]',
 'F05[N-F]',
 'F06[C-F]',
 'F07[C-F]',
 'F07[C-Br]',
 'F09[C-F]',
 'F09[N-F]',
 'F10[C-F]']

In [82]:
final_df=new_df[j]

In [83]:
final_df['Class']=new_df['Class']

C:\Users\Akshat\AppData\Local\Temp\ipykernel_18108\695168134.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Class']=new_df['Class']

In [84]:
final_df

,nF,nX,P_VSA_ppp_hal,SM03_EA(dm),nR=Cs,nR=Ct,C-005,C-006,C-016,H-053,...,F05[C-S],F05[N-N],F05[N-F],F06[C-F],F07[C-F],F07[C-Br],F09[C-F],F09[N-F],F10[C-F],Class
0,0.0,0.000000,0.00,0.406857,0.333333,0.000000,0.000000,0.000000,0.333333,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.000000,0.00,0.000000,1.000000,0.000000,0.333333,0.000000,0.833333,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.000000,0.00,0.000000,0.666667,0.333333,0.000000,0.000000,0.666667,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.066667,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
4,0.0,0.166667,0.25,0.000000,0.000000,0.000000,0.000000,0.066667,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
565,0.0,0.000000,0.00,0.146925,0.500000,0.000000,0.000000,0.133333,0.500000,0.0,...,0.181818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
566,0.0,0.000000,0.00,0.103392,0.000000,0.000000,0.666667,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
567,0.0,0.000000,0.00,0.647198,0.000000,0.000000,0.000000,0.400000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
568,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [93]:
x_trf=final_df.drop('Class',axis=1)
y_trf=final_df['Class']

In [182]:
from sklearn.model_selection import train_test_split
x_train_trf,x_test_trf,y_train_trf,y_test_trf=train_test_split(x_trf,y_trf,random_state=2,test_size=0.1)

In [183]:
np.mean(cross_val_score(clf2,x_train_trf,y_train_trf,cv=10,scoring='accuracy'))

0.7186274509803923

In [186]:
clf2=LogisticRegression()
clf3=GradientBoostingClassifier()
clf4=AdaBoostClassifier()

In [187]:
np.mean(cross_val_score(clf2,x_train_trf,y_train_trf,cv=10,scoring='accuracy'))

0.6661387631975868

In [188]:
np.mean(cross_val_score(clf3,x_train_trf,y_train_trf,cv=10,scoring='accuracy'))

0.6972473604826546

In [189]:
np.mean(cross_val_score(clf4,x_train_trf,y_train_trf,cv=10,scoring='accuracy'))

C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\Akshat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

0.5819758672699848

In [192]:
plotting_df=pd.DataFrame(columns=['Mod','Accuracy'])

In [193]:
plotting_df['Mod']=['RandomForestClassifier','GradientBoostingClassifier','LogisticRegression','AdaBoostClassifier']

In [194]:
plotting_df['Accuracy']=lst

NameError: name 'lst' is not defined